class PagesController < ApplicationController

  def home
    @title = "Home"
	@onload = 'onload = initializeMap()'
	# Need list of Contacts for the User, and list of all Comments
	# The Contacts list is generated by the rendering partial
	# The Comments list will be generated later
    if signed_in?
    #  @micropost = Micropost.new
    #  @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def help
    @title = "Help"
  end

  def about
    @title = "About"
  end

end
