class PagesController < ApplicationController

  def home
    @title = "Home"
	@onload = 'onload = initializeMap()'
	# Contacts list is generated by the view itself
	# Comments list is generated here, to paginate
    @comments = Comment.all.paginate(:page => params[:page])
  end

  def contact
    @title = "Contact"
  end

  def help
    @title = "Help"
  end

  def about
    @title = "About"
  end

end
